[project]
authors = ["Dan Allan <>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "minio-zarr"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2"
python = ">=3.12"
s3fs = "=2025.3.0"
zarr = ">=2,<3"
